name: basic demo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: a basic echo 1st job
        run: echo Hello!
  second:
    runs-on: macos-latest
    needs: [first]
    steps:
      - name: a basic echo 1st job
        run: echo Hello!
